# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      test:
        executor: node
        steps:
          - checkout
          # Restore cache at second time
          - <<: *restore_cache
          # Install for first time
          - <<: *install_node_modules
          # Cache the ./node_modules before test.
          - <<: *save_cache
          - run:
              name: Test
              command: yarn test

      build:
        executor: node
        steps:
          - checkout
          - <<: *restore_cache
          - <<: *install_node_modules
          - run:
              name: Build
              command: yarn build
          - persist_to_workspace:
              root: ./
              paths:
                - build

      deploy:
        executor: node
        steps:
          - checkout
          # Attach the pesisted built files.
          - attach_workspace:
              at: ./
          - <<: *restore_cache
          - <<: *install_node_modules
          - run:
              name: Install netlify-cli
              command: sudo npm install -g --silent netlify-cli
          - run:
              name: Deploy to Netlify
              command: netlify deploy --dir=./build -p

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master